[tools]
java = 'temurin-17.0.18+8'
ruby = "3"
uv = "0.11"

[tasks.screenshots-lossless]
description = "Lossless compress Fastlane screenshots"
run = "uv run scripts/compress_screenshots_lossless.py"

[settings.ruby]
compile = false
